movies/urls.py
from  django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static


from django.views.static import serve
from movies_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies_app/', include('movies_app.urls')),
    path(f'api/{settings.API_VERSION}/',include(('movies_app.api.urls','movies_app.api'), namespace='api-movies_app')),
    path('login/',views.MyLoginView.as_view(),name='mylogin'),
    path('logout/',views.MyLogoutView.as_view(),name='mylogout'),
    path('logeo/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',serve, {'document_root' : settings.MEDIA_ROOT,}),
        #path('media/<path>.*',serve,{'document_root' : settings.MEDIA_ROOT,})
    ]

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

movies_app/api/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from movies_app.api.viewsets import ExampleViewset, MovieViewset

# urlpatterns = [
#     # path('movie/', ExampleViewset.as_view({'get': 'list', 'post': 'create'}), name='movie-list-actions'),
#     path('movierate/', RateViewSet.as_view({'get': 'list', 'post': 'create'}), name='movierate-list-actions'),
#     path('movierate/<int:pk>/',
#          RateViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy', 'patch': 'partial_update'}),
#          name='movierate-detail-actions'),
#     path('movie/', MovieViewSet.as_view({'get': 'list', 'post': 'create'}), name='movie-list-actions'),
#     path('movie/<int:pk>/',
#          MovieViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy', 'patch': 'partial_update'}),
#          name='movie-detail-actions'),
#     path('movie-example/', ExampleViewset.as_view({'get': 'list', 'post': 'create'}), name='m-e-l-a'),
#     path('movie-example/<int:pk>/',
#          ExampleViewset.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy', 'patch': 'partial_update'}),
#          name='m-e-d-a'),
# ]

# ------------------------CHANGING TO ROUTER ---------------------------------------------
router = SimpleRouter()
router.register('movie', MovieViewset)
router.register('movierate',ExampleViewset)

urlpatterns = router.urls

movies_app/urls.py
from django.urls import path
from . import views

app_name = 'movies_app'
urlpatterns = [
    path('list_genre',views.GenreListView.as_view(),name='list_genre'),
    path('create_genre',views.GenreCreateView.as_view(),name='create_genre'),
    path('update_genre/<pk>',views.GenreUpdateView.as_view(),name='update_genre'),
    path('', views.HomeView.as_view(), name='home'),
    path('movies/<slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('form/', views.MovieFormExample.as_view(),name='simple_form'),
    path('api_list/',views.MyMoviesListView.as_view(),name='api_list'),
    path('api_detail/<slug>',views.MyMoviesDetailsView.as_view(),name='api_detail'),

    path('movie/',views.MovieCreateListView.as_view(),name='movie-li-cre'),
    path('movie/<slug>',views.MovieDetailUpdateDeleteView.as_view(),name='movie-de-up-de'),
    path('download',views.MyDownLoadView.as_view(), name='download'),
    path('suggestion',views.MySuggestionView.as_view(), name='suggestion'),

    ]

movies_app/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
import uuid

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse_lazy

from .choices import THRILLER, MOVIE_GENRE
from .queryset import *


from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify




User = get_user_model()
"""Variable to reference a system user"""


def movie_directory_path(instance,filename):
    """
    function to define store path of the posters
    Args:
        instance: image file
        filename: a string that will name the file

    Returns: path of the image storage ubication

    """
    return f'movie/{instance.title}/{filename}'


class Genre(models.Model):
    """Contains all gender of movies"""

    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Language(models.Model):
    """Contains all posible language """

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Country(models.Model):
    """Contain all contry where movies are meked"""

    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name



class Movie(models.Model):
    """Constins all information of a movie"""

    title = models.CharField(max_length=100)
    duration = models.PositiveIntegerField()
    poster = models.ImageField(upload_to=movie_directory_path)
    about = models.CharField(max_length=300, default='a movie')
    detail = models.TextField(null=True, blank=True)
    trailer_url = models.URLField(null=True, blank=True)
    genre = models.ForeignKey(Genre,on_delete=models.CASCADE)
    #genre = models.CharField(max_length=25, choices=MOVIE_GENRE, default=THRILLER)
    original_language = models.ForeignKey(Language,on_delete = models.CASCADE)
    release_date = models.DateField(null=True)
    country = models.ForeignKey(Country,on_delete=models.CASCADE)
    slug = models.CharField(max_length=100, null=True, blank=True)

    #own_objects = MovieQuerySet.as_manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('movies_app:movie_detail',args=(self.title,))

    # def save(self, force_insert=False, force_update=False, using=None,
    #          update_fields=None):
    #     self.slug = slugify(self.title)
    #     super(Movie,self).save(force_insert=force_insert,force_update=force_update, using=using,
    #                            update_fields=update_fields)


class Director(models.Model):
    """Contain all director that manage movies"""

    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    movie = models.ManyToManyField(Movie)
    alive = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Actor(models.Model):
    """Contain all actors that acts in movies"""

    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    movie = models.ManyToManyField(Movie)
    alive = models.BooleanField(default=True)
    
    def __str__(self):
        return self.name

class Rate(models.Model):
    """Contins all comments that users made"""

    rate = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(5)])
    movie = models.ForeignKey(Movie,on_delete = models.CASCADE)
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200, null=True)

    objects = MovieRateQuerySet.as_manager()

    class Meta:
        unique_together = ('user', 'movie')
        permissions = (
            ('can_vote_two_times','Can vote two times'),
        )

    def __str__(self):
        return f'{self.user.username} : {self.movie.title}'



class ValidatorToken(models.Model):
    """Storage a token for validate users"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)


class Suggestion(models.Model):
    """storage sugestion to be downloaded in loop of time [task]"""

    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

movies_app/views.py
from celery import chord, group
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DetailView, FormView
from django.urls import reverse_lazy
from django.views.generic.list import BaseListView
from rest_framework.generics import RetrieveAPIView, ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.authtoken.models import Token
#from rest_framework_xml.renderers import XMLRenderer
#import time


from django.core.management import call_command

from movies_app.models import Suggestion
from movies_app.tasks import donwload_movie, send_email
from .models import Genre, Movie, Rate, ValidatorToken
from .forms import GenreCreateForm, MovieCreateForm, SimpleForm, MyLoginForm, SimpleForm2, MyDownLoadForm, \
    MySuggestionForm

from movies_app.api.serializers import MovieOwnSerializerList, MovieOwnSerializerDetail, MovieSerializerCreateList, \
    MovieSerializerDetailUpdateDelete, MovieRateSerializer

from  rest_framework.renderers import JSONRenderer


class HomeView(ListView):
    template_name = 'home.html'
    extra_context = {'title':'My Internet Movie DataBase'}
    queryset = Movie.objects.all()
    paginate_by = 6

    def get_queryset(self):
        qs  = super(HomeView,self).get_queryset()
        return qs.order_by('-id')

    def get_context_data(self, **kwargs):
        data = super(HomeView,self).get_context_data(**kwargs)
        #data.update({'titulo':'Mi Propio Internet de Peliculas'})
        best_movie = Rate.objects.get_best_rated().first()
        if best_movie:
            movie = Movie.objects.get(pk=best_movie.get('movie'))
            data.update({
                'best_rated_movie' : movie,
                'best_rated_value' : best_movie.get('rate',0)
            })
            return data



class MovieDetailView(LoginRequiredMixin, DetailView):
    queryset = Movie.objects.all()
    template_name = 'detail.movie.html'
    slug_field = 'slug'
    query_pk_and_slug = False




class MovieFormExample(CreateView):
    template_name = 'simple.form.example.html'
    form_class = SimpleForm2
    success_url = reverse_lazy('movies_app:home')

    def form_invalid(self, form):
        print(form.errors)
        return super(MovieFormExample, self).form_invalid(form)

    def get_form_kwargs(self):
        kwargs = super(MovieFormExample, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    #def form_valid(self, form):
    #    pass

class MyDownLoadView(View):

    def __init__(self):
        self.template_name = 'download.html'
        self.form_class = MyDownLoadForm

    def get(self, request, *args, **kwargs ):
        return render(request, self.template_name, {'form':self.form_class})

    def post(self, request):
        my_form = MyDownLoadForm(request.POST)
        if my_form.is_valid():
            my_titles = my_form.cleaned_data['title_movie']
            my_reciver = my_form.cleaned_data['reciver_mail']
            my_list_movie = my_titles.split(", ")
            temp_signature = []
            for mov in my_list_movie:
                temp_signature.append(donwload_movie.s(mov))

            chord(group(*temp_signature))(send_email.s(my_reciver))

        return HttpResponseRedirect(reverse_lazy('movies_app:download'))



class MySuggestionView(View):

    def __init__(self):
        self.template_name = 'suggestion.html'
        self.form_class = MySuggestionForm

    def get(self, request, *args, **kwargs ):
        return render(request, self.template_name, {'form':self.form_class})

    def post(self, request):
        my_form = MySuggestionForm(request.POST)
        if my_form.is_valid():
            my_titles = my_form.cleaned_data['titles']
            my_list_movie = my_titles.split(", ")
            for movi in my_list_movie:
                Suggestion.objects.get_or_create(title=movi)
                Suggestion.objects

        return HttpResponseRedirect(reverse_lazy('movies_app:suggestion'))



class MyLoginView(View):

    def __init__(self):
        self.template_name = 'login.html'
        self.form_class = MyLoginForm

    def get(self, request ,*argv , **kwargs):
        return render(request,self.template_name,{'form':MyLoginForm})

    def post(self, request):
        my_form = MyLoginForm(request.POST)
        if my_form.is_valid():
            my_user = my_form.cleaned_data['username']
            my_pass = my_form.cleaned_data['password']
            the_user = authenticate(username = my_user, password=my_pass)
            Token.objects.update_or_create(user=my_user)
            if the_user is not None:
                login(request,the_user)
                if not ValidatorToken.objects.filter(user=the_user).exists():
                    vt = ValidatorToken()
                    vt.user = the_user
                    vt.save()

                return HttpResponseRedirect(reverse_lazy('movies_app:home'))
        return HttpResponse('logeo fallido')




class MyLogoutView(View):

    def get(self,request):
        my_id = request.user
        Token.objects.get(user=my_id).delete()
        #ValidatorToken.objects.get(user=my_id).delete()
        logout(request)
        return HttpResponseRedirect(reverse_lazy('mylogin'))



class GenreListView(ListView):
    model = Genre
    template_name = 'lista_genre.html'


class GenreCreateView(CreateView):
    model = Genre
    form_class = GenreCreateForm
    template_name = 'info_genre.html'
    success_url = reverse_lazy('movies_app:list_genre')


class GenreUpdateView(UpdateView):
    model = Genre
    form_class = GenreCreateForm
    template_name = 'info_genre.html'
    success_url = reverse_lazy('movies_app:list_genre')



class MyMoviesListView(BaseListView):

    model = Movie
    content_type = 'application/json'
    #content_type = 'text/xml'
    response_class = HttpResponse


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MyMoviesListView,self).get_context_data(object_list=object_list,**kwargs)
        #context.update({'serialized_data': XMLRenderer().render(MovieSerializerList(self.get_queryset(), many=True).data)})
        context.update({'serialized_data': JSONRenderer().render(MovieOwnSerializerList(self.get_queryset(),many=True).data)})
        return context

    def render_to_response(self, context, **response_kwargs):
        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            context.get('serialized_data'), **response_kwargs #content_type=self.content_type
        )




class MyMoviesDetailsView(DetailView):

    model = Movie
    content_type = 'application/json'
    response_class = HttpResponse

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MyMoviesDetailsView, self).get_context_data(object_list=object_list, **kwargs)
        context.update({'serialized_data': JSONRenderer().render(MovieOwnSerializerDetail(self.get_object()).data)})
        return context

    def render_to_response(self, context, **response_kwargs):
        response_kwargs.setdefault('content_type', self.content_type)
        return self.response_class(
            context.get('serialized_data'), **response_kwargs
        )

    def get_object(self, queryset=None):

        try:
            peli = Movie.objects.get(slug=self.kwargs['slug'])
        except Movie.DoesNotExist as e:
            call_command('download', self.kwargs['slug'])

        if peli:
            return peli
    #self.kwargs
    #call_command('download', 'titanic')  # here I need pass the slug parameter

# ----------------------------------------------------------------------------------------------
class MovieRateDetailView(RetrieveAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieRateSerializer
    lookup_field = 'slug'


class MovieCreateListView(ListCreateAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializerCreateList

class MovieDetailUpdateDeleteView(RetrieveUpdateDestroyAPIView):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializerDetailUpdateDelete
    lookup_field = 'slug'

movies_app/templates/base_movie_app.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <div class="container">
        <nav class="navbar sticky-top navbar-dark bg-dark">
            <span class="navbar-brand mb-0 h1">
                Django Movie database
            </span>
            <span class="navbar-brand mb-0 h4">
                User: {{ request.user }}
                <a href="{% url 'mylogout'%}">Logout</a>
            </span>
            <form class="form-inline">
                <input type="search" class="form-control mr-sm-2" placeholder="Search" aria-label="Search">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </nav>
    </div>
{% endblock header %}

movies_app/templates/detail.movie.html
{% extends 'base_movie_app.html' %}

{% block content %}
    {{ movie.title }}
{% endblock content %}

movies_app/templates/download.html
{% extends 'base_movie_app.html' %}

{% block content %}
    <form action="#" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Donwload">
    </form>

{% endblock content %}

movies_app/templates/home.html
{% extends 'base_movie_app.html' %}
{% load static %}

{% load movie_app_extras %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock extra_css %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-4">
                <div class="cover" style="background-image: url('{{ best_rated_movie.poster.url }}');"></div>
            </div>
            <div class="col-8">
                <h1 class="display-5">{{ best_rated_movie.title }}</h1>
                <p class="lead">{{ best_rated_value|own_format_float }} / {{ best_rated_movie.movierate_set.count }}</p>
                <p>{{ best_rated_movie.detail }}</p>
            </div>
        </div>
    </div>
    <ul><div class="row">
        {% for movie in movie_list %}

                <div class="col-4">
                    <div class="card" style="width: 18rem">
                        <img class="card-img-top" src="{{ movie.poster.url }}" alt="Card image cap">
                        <div class="card-body">
                            <a href="{% url 'movies_app:movie_detail' movie.slug %}"><h5>{{ movie.title }}</h5></a>
                            <p class="card-text">{{ movie.about }}</p>
                            <a href="{% url 'movies_app:movie_detail' movie.slug %}" class="btn btn-primary">Details</a>
                        </div>
                    </div>
                </div>

        {% endfor %} </div>
    </ul>
{% endblock content %}

{% block extra_js %}
    <script>
        console.log('Im in Home')
    </script>
{% endblock extra_js %}

movies_app/templates/info_genre.html
{% extends 'base.html' %}
<title>{% block title %}Info Genre{% endblock %}</title>

{% block content %}

    <h1>Create/Update Genre</h1>
    <form role="form" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>

{% endblock content %}

movies_app/templates/lista_genre.html
{% extends 'base.html' %}
<title>{% block title %}Lista Genre{% endblock %}</title>
{% block content %}
    <h1>LISTA</h1>
    {% if object_list %}
        {% for l in object_list %}
            {{ l.name }} - {{ l.description }} <a href="{% url 'movies_app:update_genre' l.id  %}">editar</a><br>
        {% endfor %}
    {% endif %}
{% endblock content %}

movies_app/templates/lista_movie.html
{% extends 'base.html' %}
<title>{% block title %}Lista Movie{% endblock %}</title>
    <h1>LISTA</h1>
    {% if object_list %}
        {% for l in object_list %}
            {{ l.title }} - {{ l.genre }} <a href="{% url 'movies_app:update_movie' l.id  %}">editar</a><br>
        {% endfor %}
    {% endif %}

movies_app/templates/simple.form.example.html
{% extends 'base_movie_app.html' %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Go!</button>
    </form>
{% endblock %}

movies_app/templates/suggestion.html
{% extends 'base_movie_app.html' %}

{% block content %}
    <form action="#" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Suggest">
    </form>

{% endblock content %}